const express=require('express');
const session=require('express-session');
const bcrypt=require('bcryptjs');
const multer=require('multer');
const fs=require('fs'); const path=require('path');
const app=express();
const PORT=Number(process.env.PORT||3000);
const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), DATA=path.join(ROOT,'data.json');
fs.mkdirSync(PUBLIC,{recursive:true});
const defaults={
 settings:{project_name:'GOOD MOBILE',tagline:'ТВОЙ НОВЫЙ ИГРОВОЙ МИР',hero_text:'Присоединяйся к нашему проекту и окунись в мир уникальных возможностей!',logo:'',hero_image:'',game_url:'/download/game',discord_url:'',telegram_url:'',youtube_url:'',tiktok_url:'',support_url:'',online_players:1248,today_players:87,active_players:342,maintenance:false,terms:'Используя сайт и игровой проект, вы соглашаетесь соблюдать настоящие условия, правила проекта и действующее законодательство. Администрация вправе изменять правила и ограничивать доступ при нарушениях.',privacy:'Мы используем только данные, необходимые для работы сайта, аккаунтов и административных функций. Пароли хранятся в виде безопасных хешей. Передача данных третьим лицам не осуществляется, кроме случаев, предусмотренных законом.',rules:'Запрещены мошенничество, вредоносный код, попытки взлома, обход ограничений, оскорбления, спам и использование стороннего ПО для получения нечестного преимущества.'},
 admins:[], positions:[], servers:[], links:[], news:[], applications:[], complaints:[], audit:[], downloads:0
};
function load(){try{if(!fs.existsSync(DATA)){save(defaults);return structuredClone(defaults)} const d=JSON.parse(fs.readFileSync(DATA,'utf8')); return Object.assign(structuredClone(defaults),d)}catch(e){return structuredClone(defaults)}}
let db=load(); function save(){fs.writeFileSync(DATA,JSON.stringify(db,null,2))}
let seq={}; function id(type){seq[type]=(seq[type]||0)+1; const arr=db[type]||[]; return Math.max(0,...arr.map(x=>Number(x.id)||0),seq[type])+1}
function seed(){
 if(!db.positions.length){const p=[['Руководство проекта','Полный контроль',['dashboard','admins','positions','servers','links','news','applications','complaints','settings','statistics','files','audit']],['Команда проекта','Помощь в управлении проектом',['dashboard','servers','links','news','applications','complaints']],['Помощник куратора проекта','Поддержка кураторов',['dashboard','applications','complaints']],['Специальный администратор','Выполнение особых задач',['dashboard','admins','servers','links','news','applications','complaints']],['Куратор сервера','Контроль и порядок на сервере',['dashboard','servers','applications','complaints']],['Заместитель куратора сервера','Помощь куратору сервера',['dashboard','servers','complaints']],['Старший администратор','Старший состав администрации',['dashboard','applications','complaints']],['Куратор гос.орг (8+)','Контроль государственных организаций',['dashboard','applications']],['Куратор ОПГ (4+)','Контроль преступных организаций',['dashboard','complaints']],['Администратор','Основной состав администрации',['dashboard','complaints']]];p.forEach((x,i)=>db.positions.push({id:id('positions'),name:x[0],description:x[1],permissions:x[2],sort_order:i,active:true}))}
 if(!db.servers.length) db.servers=[{id:id('servers'),name:'God Mobile #1',address:'server1.goodmobile.ru',port:7777,players:342,max_players:1000,online:true,version:'1.0',mode:'Role Play',sort_order:0},{id:id('servers'),name:'God Mobile #2',address:'server2.goodmobile.ru',port:7778,players:289,max_players:1000,online:true,version:'1.0',mode:'Role Play',sort_order:1}];
 if(!db.links.length) db.links=[{id:id('links'),title:'Discord',url:'',icon:'discord',sort_order:0,active:true},{id:id('links'),title:'Telegram',url:'',icon:'telegram',sort_order:1,active:true},{id:id('links'),title:'YouTube',url:'',icon:'youtube',sort_order:2,active:true},{id:id('links'),title:'TikTok',url:'',icon:'tiktok',sort_order:3,active:true}];
 if(!db.news.length) db.news=[{id:id('news'),title:'Добро пожаловать в Good Mobile!',excerpt:'Проект запущен. Следите за новостями и обновлениями.',content:'Добро пожаловать!',image:'',status:'PUBLISHED',created_at:new Date().toISOString(),published_at:new Date().toISOString()}];
 save();
}
seed();
app.set('trust proxy',1); app.use(express.json({limit:'5mb'})); app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'good-mobile-change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*864e5}}));
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,PUBLIC),filename:(req,file,cb)=>{if(file.fieldname==='apk')return cb(null,'game.apk'); const ext=path.extname(file.originalname).toLowerCase(); const base=path.basename(file.originalname,ext).replace(/[^a-zA-Z0-9_-]+/g,'-').slice(0,50)||'image'; cb(null,Date.now()+'-'+base+ext)}});
const upload=multer({storage,limits:{fileSize:350*1024*1024},fileFilter:(req,f,cb)=>{const ok=f.fieldname==='apk'?/\.apk$/i.test(f.originalname):/^image\/(png|jpeg|webp|gif)$/i.test(f.mimetype); cb(ok?null:new Error('Разрешены APK и PNG/JPG/WEBP/GIF'),ok)}});
function auth(req,res,next){if(!req.session.admin)return res.status(401).json({error:'Требуется вход'});next()}
function admin(){return req=>req.session.admin}
function perms(req){return req.session.admin?.permissions||[]}
function can(req,s){return req.session.admin?.role==='SUPERADMIN'||perms(req).includes(s)||s==='dashboard'}
function audit(req,action,entity,entity_id,details=''){db.audit.unshift({id:id('audit'),admin_id:req.session.admin.id,admin:req.session.admin.name,action,entity,entity_id:String(entity_id||''),details,created_at:new Date().toISOString()});db.audit=db.audit.slice(0,1000);save()}
app.get('/api/setup-status',(req,res)=>res.json({ready:db.admins.length>0}));
app.post('/api/setup',async(req,res)=>{if(db.admins.length)return res.status(409).json({error:'Владелец уже создан'}); const login=String(req.body.login||'').trim();const password=String(req.body.password||'');if(login.length<3||password.length<10)return res.status(400).json({error:'Логин от 3 символов, пароль от 10'});const hash=await bcrypt.hash(password,12);const a={id:id('admins'),login,name:String(req.body.name||'Владелец'),password_hash:hash,role:'SUPERADMIN',position:'Руководство проекта',active:true,created_at:new Date().toISOString()};db.admins.push(a);save();req.session.admin={id:a.id,login:a.login,name:a.name,role:a.role,position:a.position,permissions:db.positions[0].permissions};res.json({ok:true,user:req.session.admin})});
app.post('/api/login',async(req,res)=>{const login=String(req.body.login||'').trim().toLowerCase(), password=String(req.body.password||'');const a=db.admins.find(x=>x.active&&x.login.toLowerCase()===login);if(!a||!(await bcrypt.compare(password,a.password_hash)))return res.status(401).json({error:'Неверный логин или пароль'});const p=db.positions.find(x=>x.name===a.position);req.session.admin={id:a.id,login:a.login,name:a.name,role:a.role,position:a.position,permissions:a.role==='SUPERADMIN'?[...db.positions[0].permissions]:(p?.permissions||[])};res.json({ok:true,user:req.session.admin})});
app.get('/api/me',(req,res)=>res.json({user:req.session.admin||null})); app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/public',(req,res)=>{const s=db.settings;res.json({settings:s,servers:db.servers.filter(x=>x.online||true).sort((a,b)=>a.sort_order-b.sort_order),news:db.news.filter(x=>x.status==='PUBLISHED').sort((a,b)=>new Date(b.published_at)-new Date(a.published_at)).slice(0,8),links:db.links.filter(x=>x.active).sort((a,b)=>a.sort_order-b.sort_order),apk:fs.existsSync(path.join(PUBLIC,'game.apk')),downloads:db.downloads})});
app.get('/download/game',(req,res)=>{const f=path.join(PUBLIC,'game.apk');if(!fs.existsSync(f))return res.status(404).send('APK пока не загружен');db.downloads++;save();res.download(f,'GoodMobile.apk')});
app.get('/api/dashboard',auth,(req,res)=>{if(!can(req,'dashboard'))return res.status(403).json({error:'Нет прав'});res.json({settings:db.settings,stats:{admins:db.admins.length,positions:db.positions.length,servers:db.servers.length,news:db.news.length,applications:db.applications.length,complaints:db.complaints.length,downloads:db.downloads},servers:db.servers})});
app.get('/api/settings',auth,(req,res)=>{if(!can(req,'settings'))return res.status(403).json({error:'Нет прав'});res.json({item:db.settings})});
app.put('/api/settings',auth,(req,res)=>{if(!can(req,'settings'))return res.status(403).json({error:'Нет прав'});const allowed=['project_name','tagline','hero_text','logo','hero_image','game_url','discord_url','telegram_url','youtube_url','tiktok_url','support_url','online_players','today_players','active_players','maintenance','terms','privacy','rules'];allowed.forEach(k=>{if(req.body[k]!==undefined)db.settings[k]=req.body[k]});save();audit(req,'UPDATE','settings',1,'');res.json({item:db.settings})});
const resources={positions:['name','description','permissions','sort_order','active'],servers:['name','address','port','players','max_players','online','version','mode','sort_order'],links:['title','url','icon','sort_order','active'],news:['title','excerpt','content','image','status','published_at'],applications:['user_name','contact','position','message','status','admin_note'],complaints:['user_name','contact','subject','message','status','response','priority']};
for(const [name,fields] of Object.entries(resources)){
 app.get('/api/'+name,auth,(req,res)=>{if(!can(req,name))return res.status(403).json({error:'Нет прав'});let items=[...(db[name]||[])];const s=String(req.query.search||'').toLowerCase();if(s)items=items.filter(x=>fields.some(f=>String(x[f]??'').toLowerCase().includes(s)));res.json({items})});
 app.post('/api/'+name,auth,(req,res)=>{if(!can(req,name))return res.status(403).json({error:'Нет прав'});const x={id:id(name)};fields.forEach(f=>x[f]=req.body[f]);if(name==='positions'&&typeof x.permissions==='string'){try{x.permissions=JSON.parse(x.permissions)}catch{x.permissions=[]}};if(name==='servers'){['port','players','max_players','sort_order'].forEach(k=>x[k]=Number(x[k]||0));['online'].forEach(k=>x[k]=!!Number(x[k]??1))};if(['links'].includes(name)){x.sort_order=Number(x.sort_order||0);x.active=!!Number(x.active??1)};if(name==='news'){x.created_at=new Date().toISOString();x.published_at=x.published_at||new Date().toISOString()};db[name].push(x);save();audit(req,'CREATE',name,x.id);res.json({item:x})});
 app.put('/api/'+name+'/:id',auth,(req,res)=>{if(!can(req,name))return res.status(403).json({error:'Нет прав'});const x=db[name].find(v=>v.id==req.params.id);if(!x)return res.status(404).json({error:'Не найдено'});fields.forEach(f=>{if(req.body[f]!==undefined)x[f]=req.body[f]});if(name==='positions'&&typeof x.permissions==='string'){try{x.permissions=JSON.parse(x.permissions)}catch{x.permissions=[]}};if(['servers','links'].includes(name)){['port','players','max_players','sort_order'].forEach(k=>{if(x[k]!==undefined)x[k]=Number(x[k])});if(name==='servers')x.online=!!Number(x.online);if(name==='links')x.active=!!Number(x.active)};save();audit(req,'UPDATE',name,x.id);res.json({item:x})});
 app.delete('/api/'+name+'/:id',auth,(req,res)=>{if(!can(req,name))return res.status(403).json({error:'Нет прав'});const i=db[name].findIndex(v=>v.id==req.params.id);if(i<0)return res.status(404).json({error:'Не найдено'});const [x]=db[name].splice(i,1);save();audit(req,'DELETE',name,x.id);res.json({ok:true})});
}
app.get('/api/users',auth,(req,res)=>{if(!can(req,'admins'))return res.status(403).json({error:'Нет прав'});res.json({items:db.admins.map(({password_hash,...x})=>x)})});
app.post('/api/users',auth,async(req,res)=>{if(!can(req,'admins'))return res.status(403).json({error:'Нет прав'});const login=String(req.body.login||'').trim();if(db.admins.some(x=>x.login.toLowerCase()===login.toLowerCase()))return res.status(409).json({error:'Такой логин уже существует'});const password=String(req.body.password||'');if(password.length<10)return res.status(400).json({error:'Пароль минимум 10 символов'});const a={id:id('admins'),login,name:String(req.body.name||login),password_hash:await bcrypt.hash(password,12),role:req.body.role==='SUPERADMIN'?'SUPERADMIN':'ADMIN',position:req.body.position||'Администратор',active:true,created_at:new Date().toISOString()};db.admins.push(a);save();audit(req,'CREATE','admins',a.id);res.json({item:{...a,password_hash:undefined}})});
app.put('/api/users/:id',auth,async(req,res)=>{if(!can(req,'admins'))return res.status(403).json({error:'Нет прав'});const a=db.admins.find(x=>x.id==req.params.id);if(!a)return res.status(404).json({error:'Не найдено'});['login','name','position','active'].forEach(k=>{if(req.body[k]!==undefined)a[k]=k==='active'?!!Number(req.body[k]):req.body[k]});if(req.body.role)a.role=req.body.role==='SUPERADMIN'?'SUPERADMIN':'ADMIN';if(req.body.password){if(String(req.body.password).length<10)return res.status(400).json({error:'Пароль минимум 10 символов'});a.password_hash=await bcrypt.hash(String(req.body.password),12)}save();audit(req,'UPDATE','admins',a.id);res.json({item:{...a,password_hash:undefined}})});
app.delete('/api/users/:id',auth,(req,res)=>{if(!can(req,'admins'))return res.status(403).json({error:'Нет прав'});if(Number(req.params.id)===req.session.admin.id)return res.status(400).json({error:'Нельзя удалить себя'});db.admins=db.admins.filter(x=>x.id!=req.params.id);save();audit(req,'DELETE','admins',req.params.id);res.json({ok:true})});
app.get('/api/audit',auth,(req,res)=>{if(!can(req,'audit'))return res.status(403).json({error:'Нет прав'});res.json({items:db.audit})});
app.get('/api/files',auth,(req,res)=>{if(!can(req,'files'))return res.status(403).json({error:'Нет прав'});res.json({files:fs.readdirSync(PUBLIC).filter(x=>x!=='index.html').map(name=>{const st=fs.statSync(path.join(PUBLIC,name));return {name,size:st.size,url:'/'+encodeURIComponent(name),modified:st.mtime}}),apk:fs.existsSync(path.join(PUBLIC,'game.apk'))})});
app.post('/api/upload/apk',auth,(req,res)=>{if(!can(req,'files')&&req.session.admin.role!=='SUPERADMIN')return res.status(403).json({error:'Нет прав'});upload.single('apk')(req,res,e=>{if(e)return res.status(400).json({error:e.message});if(!req.file)return res.status(400).json({error:'Выбери APK'});res.json({ok:true,file:req.file.filename,size:req.file.size})})});
app.post('/api/upload/image',auth,(req,res)=>{if(!can(req,'files')&&req.session.admin.role!=='SUPERADMIN')return res.status(403).json({error:'Нет прав'});upload.single('image')(req,res,e=>{if(e)return res.status(400).json({error:e.message});if(!req.file)return res.status(400).json({error:'Выбери изображение'});res.json({ok:true,file:req.file.filename,url:'/'.concat(encodeURIComponent(req.file.filename))})})});
app.delete('/api/files/:name',auth,(req,res)=>{if(!can(req,'files'))return res.status(403).json({error:'Нет прав'});const n=path.basename(req.params.name);if(n==='game.apk')return res.status(400).json({error:'APK удаляй отдельной кнопкой'});const f=path.join(PUBLIC,n);if(!fs.existsSync(f))return res.status(404).json({error:'Файл не найден'});fs.unlinkSync(f);res.json({ok:true})});
app.delete('/api/files/apk',auth,(req,res)=>{if(!can(req,'files'))return res.status(403).json({error:'Нет прав'});const f=path.join(PUBLIC,'game.apk');if(fs.existsSync(f))fs.unlinkSync(f);res.json({ok:true})});
app.use(express.static(PUBLIC));
app.get('*',(req,res)=>res.sendFile(path.join(PUBLIC,'index.html')));
app.use((err,req,res,next)=>res.status(500).json({error:err.message||'Ошибка сервера'}));
app.listen(PORT,()=>console.log('Good Mobile running on '+PORT));
