const express=require("express");
const session=require("express-session");
const bcrypt=require("bcryptjs");
const {Pool}=require("pg");
const multer=require("multer");
const path=require("path");
const fs=require("fs");
const app=express();
const PORT=Number(process.env.PORT||3000);
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
app.use(express.json({limit:"2mb"})); app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||"change-this",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:604800000}}));
app.use(express.static(path.join(__dirname,"public")));
const upload=multer({storage:multer.diskStorage({destination:(_,__,cb)=>cb(null,path.join(__dirname,"public")),filename:(_,file,cb)=>cb(null,file.fieldname==="apk"?"game.apk":`${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g,"_")}`)}),limits:{fileSize:300*1024*1024},fileFilter:(_,f,cb)=>{const ok=f.fieldname==="apk"?/\.apk$/i.test(f.originalname):/image\/(png|jpeg|webp|gif)/i.test(f.mimetype);cb(ok?null:new Error("Недопустимый тип файла"),ok)}});

async function q(text,args=[]){return (await pool.query(text,args)).rows}
async function init(){
 await q(`CREATE TABLE IF NOT EXISTS admins(id SERIAL PRIMARY KEY,login TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'ADMIN',position TEXT DEFAULT 'Администратор',active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS positions(id SERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,description TEXT DEFAULT '',permissions JSONB DEFAULT '[]',sort_order INT DEFAULT 0,active BOOLEAN DEFAULT TRUE);
 CREATE TABLE IF NOT EXISTS servers(id SERIAL PRIMARY KEY,name TEXT NOT NULL,address TEXT DEFAULT '',port INT DEFAULT 7777,players INT DEFAULT 0,max_players INT DEFAULT 1000,online BOOLEAN DEFAULT TRUE,version TEXT DEFAULT '1.0',mode TEXT DEFAULT 'Role Play',sort_order INT DEFAULT 0);
 CREATE TABLE IF NOT EXISTS links(id SERIAL PRIMARY KEY,title TEXT NOT NULL,url TEXT NOT NULL,icon TEXT DEFAULT 'link',sort_order INT DEFAULT 0,active BOOLEAN DEFAULT TRUE);
 CREATE TABLE IF NOT EXISTS news(id SERIAL PRIMARY KEY,title TEXT NOT NULL,excerpt TEXT DEFAULT '',content TEXT DEFAULT '',image TEXT DEFAULT '',status TEXT DEFAULT 'PUBLISHED',created_at TIMESTAMPTZ DEFAULT now(),published_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS applications(id SERIAL PRIMARY KEY,user_name TEXT NOT NULL,contact TEXT DEFAULT '',position TEXT DEFAULT '',message TEXT DEFAULT '',status TEXT DEFAULT 'NEW',admin_note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS complaints(id SERIAL PRIMARY KEY,user_name TEXT NOT NULL,contact TEXT DEFAULT '',subject TEXT DEFAULT '',message TEXT DEFAULT '',status TEXT DEFAULT 'NEW',response TEXT DEFAULT '',priority TEXT DEFAULT 'NORMAL',created_at TIMESTAMPTZ DEFAULT now());
 CREATE TABLE IF NOT EXISTS settings(id INT PRIMARY KEY DEFAULT 1,project_name TEXT DEFAULT 'GOOD MOBILE',tagline TEXT DEFAULT 'ТВОЙ НОВЫЙ ИГРОВОЙ МИР',hero_text TEXT DEFAULT 'Присоединяйся к нашему проекту и окунись в мир уникальных возможностей!',logo TEXT DEFAULT '',hero_image TEXT DEFAULT '',game_url TEXT DEFAULT '/download/game',discord_url TEXT DEFAULT '',telegram_url TEXT DEFAULT '',youtube_url TEXT DEFAULT '',tiktok_url TEXT DEFAULT '',support_url TEXT DEFAULT '',online_players INT DEFAULT 0,today_players INT DEFAULT 0,active_players INT DEFAULT 0,maintenance BOOLEAN DEFAULT FALSE,terms TEXT DEFAULT 'Используя сайт и проект, вы соглашаетесь соблюдать правила проекта и действующее законодательство.',privacy TEXT DEFAULT 'Мы обрабатываем только данные, необходимые для работы аккаунта и предоставления сервисов.',rules TEXT DEFAULT 'Запрещены мошенничество, вредоносное ПО, оскорбления и обход ограничений проекта.');
 CREATE TABLE IF NOT EXISTS audit(id SERIAL PRIMARY KEY,admin_id INT,action TEXT,entity TEXT,entity_id TEXT,details TEXT,created_at TIMESTAMPTZ DEFAULT now());`);
 await q(`INSERT INTO settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING`);
 const p=[["Руководство проекта","Полный контроль",["dashboard","admins","positions","servers","links","news","applications","complaints","settings","statistics","audit"]],["Команда проекта","Управление проектом",["dashboard","servers","links","news","applications","complaints"]],["Помощник куратора проекта","Помощь кураторам",["dashboard","applications","complaints"]],["Специальный администратор","Расширенные права",["dashboard","admins","positions","servers","links","news","applications","complaints"]],["Куратор сервера","Контроль сервера",["dashboard","servers","applications","complaints"]],["Заместитель куратора сервера","Помощь куратору",["dashboard","servers","complaints"]],["Старший администратор","Старшая администрация",["dashboard","applications","complaints"]],["Куратор гос.орг (8+)","Куратор гос. организаций",["dashboard","applications"]],["Куратор ОПГ (4+)","Куратор ОПГ",["dashboard","complaints"]],["Администратор","Базовая администрация",["dashboard","complaints"]]];
 for(let i=0;i<p.length;i++) await q(`INSERT INTO positions(name,description,permissions,sort_order) VALUES($1,$2,$3,$4) ON CONFLICT(name) DO NOTHING`,[p[i][0],p[i][1],JSON.stringify(p[i][2]),i]);
}
function auth(req,res,next){if(!req.session.admin)return res.status(401).json({error:"Требуется авторизация"});next()}
function allowed(section){return (req)=>req.session.admin.role==="SUPERADMIN"||req.session.admin.permissions.includes(section)||section==="dashboard"}
async function audit(req,action,entity,id,details=""){await q(`INSERT INTO audit(admin_id,action,entity,entity_id,details) VALUES($1,$2,$3,$4,$5)`,[req.session.admin.id,action,entity,String(id||""),details])}
app.post("/api/login",async(req,res)=>{try{const login=String(req.body.login||"").trim().toLowerCase(),password=String(req.body.password||"");const a=(await q(`SELECT a.*,p.permissions FROM admins a LEFT JOIN positions p ON p.name=a.position WHERE lower(a.login)=lower($1) AND a.active=true`,[login]))[0];if(!a||!(await bcrypt.compare(password,a.password_hash)))return res.status(401).json({error:"Неверный логин или пароль"});req.session.admin={id:a.id,login:a.login,name:a.name,role:a.role,position:a.position,permissions:Array.isArray(a.permissions)?a.permissions:[]};res.json({ok:true,user:req.session.admin})}catch(e){res.status(500).json({error:"Ошибка входа"})}});
app.post("/api/setup",async(req,res)=>{try{if((await q("SELECT count(*)::int n FROM admins"))[0].n>0)return res.status(409).json({error:"Владелец уже создан"});const login=String(req.body.login||"").trim(),password=String(req.body.password||"");if(login.length<3||password.length<10)return res.status(400).json({error:"Логин от 3 символов, пароль от 10"});const hash=await bcrypt.hash(password,12);const a=(await q(`INSERT INTO admins(login,name,password_hash,role,position) VALUES($1,$2,$3,'SUPERADMIN','Руководство проекта') RETURNING id,login,name,role,position`,[login,String(req.body.name||"Владелец"),hash]))[0];req.session.admin={...a,permissions:["dashboard","admins","positions","servers","links","news","applications","complaints","settings","statistics","audit"]};res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/me",async(req,res)=>res.json({user:req.session.admin||null}));
app.post("/api/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/setup-status",async(_,res)=>{try{res.json({ready:(await q("SELECT count(*)::int n FROM admins"))[0].n>0})}catch(e){res.status(500).json({error:"PostgreSQL недоступен"})}});
app.get("/api/public",async(_,res)=>{const settings=(await q("SELECT * FROM settings WHERE id=1"))[0];const servers=await q("SELECT * FROM servers ORDER BY sort_order,id");const news=await q("SELECT * FROM news WHERE status='PUBLISHED' ORDER BY published_at DESC,id DESC LIMIT 8");const links=await q("SELECT * FROM links WHERE active=true ORDER BY sort_order,id");res.json({settings,servers,news,links})});
const resource={
positions:{table:"positions",fields:["name","description","permissions","sort_order","active"]},
servers:{table:"servers",fields:["name","address","port","players","max_players","online","version","mode","sort_order"]},
links:{table:"links",fields:["title","url","icon","sort_order","active"]},
news:{table:"news",fields:["title","excerpt","content","image","status","published_at"]},
applications:{table:"applications",fields:["user_name","contact","position","message","status","admin_note"]},
complaints:{table:"complaints",fields:["user_name","contact","subject","message","status","response","priority"]}
};
for(const [name,c] of Object.entries(resource)){
 app.get(`/api/${name}`,auth,async(req,res)=>{if(!allowed(name)(req))return res.status(403).json({error:"Нет прав"});const s=String(req.query.search||"");const cond=c.fields.filter(f=>["name","title","user_name","subject","address","description"].includes(f)).map(f=>`${f}::text ILIKE $1`).join(" OR ");const sql=`SELECT * FROM ${c.table} ${s&&cond?`WHERE ${cond}`:""} ORDER BY id DESC`;res.json({items:await q(sql,s?[`%${s}%`]:[])})});
 app.post(`/api/${name}`,auth,async(req,res)=>{if(!allowed(name)(req))return res.status(403).json({error:"Нет прав"});const vals=c.fields.map(f=>f==="permissions"?JSON.stringify(req.body[f]||[]):req.body[f]);const sql=`INSERT INTO ${c.table} (${c.fields.join(",")}) VALUES (${c.fields.map((_,i)=>"$"+(i+1)).join(",")}) RETURNING *`;const row=(await q(sql,vals))[0];await audit(req,"CREATE",name,row.id,JSON.stringify(req.body).slice(0,1000));res.json({item:row})});
 app.put(`/api/${name}/:id`,auth,async(req,res)=>{if(!allowed(name)(req))return res.status(403).json({error:"Нет прав"});const sets=c.fields.map((f,i)=>`${f}=$${i+1}`),vals=c.fields.map(f=>f==="permissions"?JSON.stringify(req.body[f]||[]):req.body[f]);vals.push(req.params.id);const row=(await q(`UPDATE ${c.table} SET ${sets.join(",")} WHERE id=$${vals.length} RETURNING *`,vals))[0];if(!row)return res.status(404).json({error:"Не найдено"});await audit(req,"UPDATE",name,row.id,"");res.json({item:row})});
 app.delete(`/api/${name}/:id`,auth,async(req,res)=>{if(!allowed(name)(req))return res.status(403).json({error:"Нет прав"});await q(`DELETE FROM ${c.table} WHERE id=$1`,[req.params.id]);await audit(req,"DELETE",name,req.params.id,"");res.json({ok:true})});
}
app.get("/api/users",auth,async(req,res)=>{if(!allowed("admins")(req))return res.status(403).json({error:"Нет прав"});res.json({items:await q("SELECT id,login,name,role,position,active,created_at FROM admins ORDER BY id DESC")})});
app.post("/api/users",auth,async(req,res)=>{if(!allowed("admins")(req))return res.status(403).json({error:"Нет прав"});if(String(req.body.password||"").length<10)return res.status(400).json({error:"Пароль минимум 10 символов"});const hash=await bcrypt.hash(req.body.password,12);const a=(await q(`INSERT INTO admins(login,name,password_hash,role,position,active) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,login,name,role,position,active`,[req.body.login,req.body.name,hash,req.body.role||"ADMIN",req.body.position||"Администратор",req.body.active!==false]))[0];await audit(req,"CREATE","admins",a.id,a.login);res.json({item:a})});
app.put("/api/users/:id",auth,async(req,res)=>{if(!allowed("admins")(req))return res.status(403).json({error:"Нет прав"});let fields=["name","role","position","active"],vals=fields.map(f=>req.body[f]);if(req.body.password){fields.push("password_hash");vals.push(await bcrypt.hash(req.body.password,12))}vals.push(req.params.id);const a=(await q(`UPDATE admins SET ${fields.map((f,i)=>`${f}=$${i+1}`).join(",")} WHERE id=$${vals.length} RETURNING id,login,name,role,position,active`,vals))[0];await audit(req,"UPDATE","admins",a.id,a.login);res.json({item:a})});
app.delete("/api/users/:id",auth,async(req,res)=>{if(!allowed("admins")(req))return res.status(403).json({error:"Нет прав"});if(Number(req.params.id)===req.session.admin.id)return res.status(400).json({error:"Нельзя удалить себя"});await q("DELETE FROM admins WHERE id=$1",[req.params.id]);await audit(req,"DELETE","admins",req.params.id,"");res.json({ok:true})});
app.get("/api/settings",auth,async(req,res)=>{if(!allowed("settings")(req))return res.status(403).json({error:"Нет прав"});res.json({item:(await q("SELECT * FROM settings WHERE id=1"))[0]})});
app.put("/api/settings",auth,async(req,res)=>{if(!allowed("settings")(req))return res.status(403).json({error:"Нет прав"});const keys=["project_name","tagline","hero_text","logo","hero_image","game_url","discord_url","telegram_url","youtube_url","tiktok_url","support_url","online_players","today_players","active_players","maintenance","terms","privacy","rules"];const sets=keys.map((k,i)=>`${k}=$${i+1}`);const vals=keys.map(k=>req.body[k]);await q(`UPDATE settings SET ${sets.join(",")} WHERE id=1`,vals);await audit(req,"UPDATE","settings",1,"");res.json({ok:true})});
app.get("/api/dashboard",auth,async(req,res)=>{const settings=(await q("SELECT * FROM settings WHERE id=1"))[0];const stats=(await q(`SELECT (SELECT count(*) FROM admins)::int admins,(SELECT count(*) FROM servers)::int servers,(SELECT count(*) FROM news)::int news,(SELECT count(*) FROM applications)::int applications,(SELECT count(*) FROM complaints)::int complaints`))[0];res.json({settings,stats,servers:await q("SELECT * FROM servers ORDER BY sort_order,id")})});
app.get("/api/audit",auth,async(req,res)=>{if(!allowed("audit")(req))return res.status(403).json({error:"Нет прав"});res.json({items:await q("SELECT audit.*,admins.name FROM audit LEFT JOIN admins ON admins.id=audit.admin_id ORDER BY audit.id DESC LIMIT 300")})});
app.post("/api/upload/apk",auth,upload.single("apk"),async(req,res)=>{if(!allowed("settings")(req))return res.status(403).json({error:"Нет прав"});if(!req.file)return res.status(400).json({error:"Файл не выбран"});await q("UPDATE settings SET game_url='/download/game' WHERE id=1");await audit(req,"UPLOAD","apk","game",req.file.originalname);res.json({ok:true,file:"/download/game"})});
app.post("/api/upload/image",auth,upload.single("image"),async(req,res)=>{if(!allowed("settings")(req))return res.status(403).json({error:"Нет прав"});if(!req.file)return res.status(400).json({error:"Файл не выбран"});await audit(req,"UPLOAD","image",req.file.filename,req.file.originalname);res.json({ok:true,url:"/"+req.file.filename})});
app.get("/download/game",(req,res)=>{const f=path.join(__dirname,"public","game.apk");if(!fs.existsSync(f))return res.status(404).send("APK пока не загружен");res.download(f,"GoodMobile.apk")});
app.use((req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
init().then(()=>app.listen(PORT,()=>console.log("Good Mobile Panel listening on "+PORT))).catch(e=>{console.error(e);process.exit(1)});
